title: Infinite Flight 中文文档
description: Infinite Flight 中文翻译文档
lang: zh-CN
theme: jekyll-theme-primer
include:
  - _images
  - atc-guide/_radar
  - scenery-editor-manual/11.-airport-gates/_11.1-gate-equipment-placement.md
defaults:
  - scope:
      path: ""
    values:
      layout: default
